org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# 🎯 Прямое указание пути к рабочему AAPT2 (обходим баг Windows)
android.aapt2FromMavenOverride=C:/Users/alexx/AppData/Local/Android/Sdk/build-tools/34.0.0/aapt2.exe